config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/oeg-upm/fair_ontologies:
      branch: main
      repo: https://github.com/oeg-upm/fair_ontologies.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/oeg-upm/fair_ontologies git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ecru-burmese.sh
        container: qc.acc_craggy-platinum-woodlouse
  QC.Doc:
    repos:
      github.com/oeg-upm/fair_ontologies find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cinnabar-warthog.sh
        container: qc.doc_jumpy-eggplant-quokka
      github.com/oeg-upm/fair_ontologies git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-carmine-chicken.sh
        container: qc.doc_cozy-cerulean-caterpillar
      github.com/oeg-upm/fair_ontologies markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-olivine-bat.sh
        container: qc.doc_wheezy-myrtle-capybara
  QC.Lic:
    repos:
      github.com/oeg-upm/fair_ontologies licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-lime-wallaby.sh
        container: qc.lic_pasty-sapphire-sheepdog
  QC.Met:
    repos:
      github.com/oeg-upm/fair_ontologies cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-brass-audemer.sh
        container: qc.met_wimpy-olivine-cichlid
  QC.Sty:
    repos:
      github.com/oeg-upm/fair_ontologies checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-denim-frise.sh
        container: qc.sty_grumpy-cream-shark
      github.com/oeg-upm/fair_ontologies jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-denim-wombat.sh
        container: qc.sty_freaky-bistre-maltese
  QC.Ver:
    repos:
      github.com/oeg-upm/fair_ontologies get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-sepia-bloodhound.sh
        container: qc.ver_shaky-asparagus-sloth
timeout: 5400
